<?php

/**
 * @file
 * Code for the event stat feature.
 */

include_once 'event_stat.features.inc';

function event_stat_field_group_build_pre_render_alter(&$element) {
  $element['ding_campaigns_wrap']['#access'] = FALSE;
  $element['language']['#access'] = FALSE;

  if (isset($element['group_efterbehandling']) && ($element['#id'] == 'ding-event-node-form')) {
    global $user;
    $rid = array_search('Event rapportør', $user->roles);
    $admin = array_search('administrator', $user->roles);
    $role = count($user->roles);
    if (user_has_role($rid) && ($role == '2')) {
       if (!empty( $element['#node']->nid)) {
          $element['title']['#attributes']['readonly'] = TRUE;
       }
       
       $element['options']['#attributes']['onclick'] = 'return false;';
       $element['author']['#access'] = FALSE;
       $element['revision_information']['#access'] = FALSE;
       $element['capacity']['#access'] = FALSE;
       $element['place2book']['#access'] = FALSE;
       $element['additional_settings']['#attributes']['onclick'] = 'return false;';
       $sdato =  DateTime::createFromFormat('Y-m-d H:i:s', $element['group_ding_event_date_loc_price']['field_ding_event_date']['und'][0]['#default_value']['value']);
       $date = $sdato->format('m/d/Y H:i');
       $element['group_efterbehandling']['field_slutdato']['und'][0]['#title'] = '<br />Startdato: ' . $date . '<br /><br />Slutdato';
       
       $element['group_ding_event_date_loc_price'] += array(
        '#states' => array(
        'invisible' => array(
        'input[name="field_efterbehandling_workflow[und][0][workflow][workflow_sid]"]' => array('checked' => TRUE),
          ),
        '#id' => 'field_ding_event_date',
        )
      );

      $name = $element['field_efterbehandling_workflow']['und'][0]['workflow']['workflow_sid']['#options'];
      $key = array_search ('Ubehandlet', $name);
      $element['group_efterbehandling'] += array(
      '#states' => array(
        'invisible' => array(
         'input[name="field_efterbehandling_workflow[und][0][workflow][workflow_sid]"]' => array('value' => $key),
        ),
      '#id' => 'group_efterbehandling',
      )
    );

     }
     elseif(user_has_role($admin)) {
        $name = $element['field_efterbehandling_workflow']['und'][0]['workflow']['workflow_sid']['#options'];
        $ubehandlet = array_search ('Ubehandlet', $name);
        $element['group_efterbehandling'] += array(
        '#states' => array(
        'invisible' => array(
         'input[name="field_efterbehandling_workflow[und][0][workflow][workflow_sid]"]' => array('value' => $ubehandlet),
            ),
            '#id' => 'group_efterbehandling',
        )
        );
        }
         else{
         $element['field_efterbehandling_workflow']['#access'] = FALSE;
         $element['group_efterbehandling']['#access'] = FALSE;
     }
  }
}

function event_stat_enable(){
$fname = 'event_stat_user_default_permissions';
$feature = features_get_features($fname);
$components = array_keys($feature->info['features']);
features_revert(array($fname => $components));
drupal_flush_all_caches();
}