<?php

/**
 * @file
 * event_stat.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function event_stat_field_default_field_instances() {
    $field_instances = array();

    // Exported field_instance: 'node-ding_event-field_antal_deltagere'
    $field_instances['node-ding_event-field_antal_deltagere'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => 'Anslås, hvis der ikke er et specifikt antal, fx ved arrangementer af ”messetype”',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 20,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_antal_deltagere',
      'label' => 'Antal deltagere',
      'required' => 1,
      'settings' => array(
        'max' => 9999,
        'min' => '',
        'prefix' => '',
        'suffix' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'number',
        'settings' => array(),
        'type' => 'number',
        'weight' => 19,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_antal_udervisere'
    $field_instances['node-ding_event-field_antal_udervisere'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 22,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_antal_udervisere',
      'label' => 'Antal undervisere',
      'required' => 1,
      'settings' => array(
        'max' => 10,
        'min' => '',
        'prefix' => '',
        'suffix' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'number',
        'settings' => array(),
        'type' => 'number',
        'weight' => 20,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_arrangementstype'
    $field_instances['node-ding_event-field_arrangementstype'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 30,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_arrangementstype',
      'label' => 'Arrangementstype',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 18,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_bem_rkninger'
    $field_instances['node-ding_event-field_bem_rkninger'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 31,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_bem_rkninger',
      'label' => 'Bemærkninger',
      'required' => 0,
      'settings' => array(
        'text_processing' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => 5,
        ),
        'type' => 'text_textarea',
        'weight' => 30,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_efterbehandling_workflow'
    $field_instances['node-ding_event-field_efterbehandling_workflow'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 29,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_efterbehandling_workflow',
      'label' => 'Efterbehandling workflow',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'workflowfield',
        'settings' => array(
          'comment' => 1,
          'fieldset' => 0,
          'name_as_title' => 1,
        ),
        'type' => 'workflow_default',
        'weight' => 10,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_ekstern_underviser'
    $field_instances['node-ding_event-field_ekstern_underviser'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 26,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ekstern_underviser',
      'label' => 'Har der været ekstern oplægsholder/underviser/musiker?',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 26,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_eksterne_partnere'
    $field_instances['node-ding_event-field_eksterne_partnere'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 24,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_eksterne_partnere',
      'label' => 'Er arrangementet lavet i samarbejde med eksterne partnere?',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 23,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_forberedelsestid'
    $field_instances['node-ding_event-field_forberedelsestid'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => 'Anslås bedst muligt',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 23,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_forberedelsestid',
      'label' => 'Forberedelsestid i minutter',
      'required' => 0,
      'settings' => array(
        'max' => '',
        'min' => '',
        'prefix' => '',
        'suffix' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'number',
        'settings' => array(),
        'type' => 'number',
        'weight' => 22,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_har_formidlingen_v_ret_inv'
    $field_instances['node-ding_event-field_har_formidlingen_v_ret_inv'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 34,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_har_formidlingen_v_ret_inv',
      'label' => 'Har Formidlingen været involveret ifm. Markedsføring',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 25,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_hvilken_art'
    $field_instances['node-ding_event-field_hvilken_art'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 25,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_hvilken_art',
      'label' => 'Hvis Ja, af hvilken art - økonomisk eller andet. Angiv hvem og hvad der støttes med?',
      'required' => 1,
      'settings' => array(
        'text_processing' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => 5,
        ),
        'type' => 'text_textarea',
        'weight' => 24,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_initialer'
    $field_instances['node-ding_event-field_initialer'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 33,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_initialer',
      'label' => 'Ansvarlig (initialer)',
      'required' => 1,
      'settings' => array(
        'text_processing' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => 4,
        ),
        'type' => 'text_textfield',
        'weight' => 29,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_kategori'
    $field_instances['node-ding_event-field_kategori'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 21,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_kategori',
      'label' => 'Kategori',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 17,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_kvaliteten'
    $field_instances['node-ding_event-field_kvaliteten'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 28,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_kvaliteten',
      'label' => 'Hvis ja, hvordan oplevede du kvaliteten af denne?',
      'required' => 1,
      'settings' => array(
        'text_processing' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => 5,
        ),
        'type' => 'text_textarea',
        'weight' => 27,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_omkostninger'
    $field_instances['node-ding_event-field_omkostninger'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 27,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_omkostninger',
      'label' => 'Omkostninger til oplægsholder/underviser/musiker',
      'required' => 1,
      'settings' => array(
        'max' => '',
        'min' => '',
        'prefix' => '',
        'suffix' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'number',
        'settings' => array(),
        'type' => 'number',
        'weight' => 28,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_slutdato'
    $field_instances['node-ding_event-field_slutdato'] = array(
      'bundle' => 'ding_event',
      'default_value' => array(),
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'date',
          'settings' => array(
            'format_type' => 'long',
            'fromto' => 'both',
            'multiple_from' => '',
            'multiple_number' => '',
            'multiple_to' => '',
          ),
          'type' => 'date_default',
          'weight' => 32,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_slutdato',
      'label' => 'Slutdato',
      'required' => 0,
      'settings' => array(
        'default_value' => 'blank',
        'default_value2' => 'same',
        'default_value_code' => '',
        'default_value_code2' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'date',
        'settings' => array(
          'display_all_day' => 0,
          'increment' => 1,
          'input_format' => 'm/d/Y - H:i:s',
          'input_format_custom' => '',
          'label_position' => 'above',
          'text_parts' => array(),
          'year_range' => '-3:+3',
        ),
        'type' => 'date_select',
        'weight' => 21,
      ),
    );

    // Exported field_instance: 'node-ding_event-field_type'
    $field_instances['node-ding_event-field_type'] = array(
      'bundle' => 'ding_event',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 35,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser_highlight' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_type',
      'label' => 'Type',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 16,
      ),
    );

    // Translatables
    // Included for use with string extractors like potx.
    t('Anslås bedst muligt');
    t('Anslås, hvis der ikke er et specifikt antal, fx ved arrangementer af ”messetype”');
    t('Ansvarlig (initialer)');
    t('Antal deltagere');
    t('Antal undervisere');
    t('Arrangementstype');
    t('Bemærkninger');
    t('Efterbehandling workflow');
    t('Er arrangementet lavet i samarbejde med eksterne partnere?');
    t('Forberedelsestid i minutter');
    t('Har Formidlingen været involveret ifm. Markedsføring');
    t('Har der været ekstern oplægsholder/underviser/musiker?');
    t('Hvis Ja, af hvilken art - økonomisk eller andet. Angiv hvem og hvad der støttes med?');
    t('Hvis ja, hvordan oplevede du kvaliteten af denne?');
    t('Kategori');
    t('Omkostninger til oplægsholder/underviser/musiker');
    t('Slutdato');
    t('Type');

    return $field_instances;
}
